(EXPERT_MASTER_SCHEMATIC
  (VERSION 2.9-HIGHEST)
  (TITLE "Extreme Performance Laptop - Aerospace Grade Schematic (Fully Consolidated)")

  ;; Power Domains
  (NET NET_PWR_CORE_1V2 (SOURCE VRM_TI_TPS) (LOAD CPU_INTEL_I9_14900HX, GPU_NVIDIA_ADA5090M, GPU_NANOWIRE_AI_QUANTUM, NPU_INTEL_TOPS45))
  (NET NET_PWR_MEM_1V1 (SOURCE VRM_TI_TPS) (LOAD MEMORY_DDR5X_MICRON[4 DIMMs]))
  (NET NET_PWR_HBM (SOURCE VRM_TI_TPS) (LOAD MEMORY_HBM3_STACK))
  (NET NET_PWR_GPU_1V8 (SOURCE MOSFET_INFINEON_OPTIMOS) (LOAD GPU_NVIDIA_ADA5090M))
  (NET NET_PWR_BATT_11V1 (SOURCE SOLID_STATE_BATTERY) (LOAD SYSTEM_DC_RAILS))
  (NET NET_PWR_IO_3V3 (SOURCE PMIC_NXP) (LOAD NFC_MODULE_HP, THUNDERBOLT5_CONTROLLER, TPM_INFINEON, SD_EXPRESS_SLOT, WWAN_MODULE_QUALCOMM_X90, WIFI7_BT_QUALCOMM_FASTCONNECT, TELEPHONE_MODEM, FAX_CONTROLLER, ETHERNET_CAT8_CONTROLLER, USB2_CONTROLLER, USB3_2_CONTROLLER, USB4_CONTROLLER))
  (NET NET_PWR_USB_EPR_48V (SOURCE PORT_USB_PD) (LOAD DC_DC_CONVERTER))

  ;; High-Speed Differential & Communication Interfaces
  (NET NET_PCIE_GPU (DIFF_PAIR TRUE IMPEDANCE "100Ω differential") (CONNECTION CPU_INTEL_I9_14900HX.PCIe_TX -> GPU_NVIDIA_ADA5090M.PCIe_RX))
  (NET NET_DDR5_BUS (WIDTH "128 bits") (CONNECTION CPU_INTEL_I9_14900HX.DDR5_CTRL -> MEMORY_DDR5X_MICRON.DATA))
  (NET NET_HBM_STACK (WIDTH "1024 bits") (CONNECTION GPU_NVIDIA_ADA5090M.HBM_CTRL -> MEMORY_HBM3_STACK.CTRL))
  (NET NET_PCIE_TB5 (DIFF_PAIR TRUE IMPEDANCE "85Ω differential") (CONNECTION CPU_INTEL_I9_14900HX.PCIe_TX -> THUNDERBOLT5_CONTROLLER.PCIe_RX))
  (NET NET_PCIE_WWAN (DIFF_PAIR TRUE IMPEDANCE "85Ω differential") (CONNECTION CPU_INTEL_I9_14900HX.PCIe_TX -> WWAN_MODULE_QUALCOMM_X90.PCIe_RX))
  (NET NET_PCIE_WIFI (DIFF_PAIR TRUE IMPEDANCE "85Ω differential") (CONNECTION CPU_INTEL_I9_14900HX.PCIe_TX -> WIFI7_BT_QUALCOMM_FASTCONNECT.PCIe_RX))
  (NET NET_ETHERNET_CAT8 (DIFF_PAIR TRUE IMPEDANCE "100Ω differential") (CONNECTION ETHERNET_CAT8_CONTROLLER.TX -> RJ45_PORT_CAT8.RX))
  (NET NET_USB_4_BUS (DIFF_PAIR TRUE IMPEDANCE "85Ω differential") (CONNECTION USB4_CONTROLLER.TX -> PORT_USB4[2 PORTS].RX))
  (NET NET_USB_3_2_BUS (WIDTH "SuperSpeed") (CONNECTION USB3_2_CONTROLLER.DATA -> PORT_USB3_2[2 PORTS].DATA))
  (NET NET_USB_2_BUS (CONNECTION USB2_CONTROLLER.DATA -> PORT_USB2_0[1 PORT].DATA))
  (NET NET_TELEPHONE_LINE (CONNECTION TELEPHONE_MODEM.TX_RX -> RJ11_PORT_PHONE.PIN))
  (NET NET_FAX_LINE (CONNECTION FAX_CONTROLLER.TX_RX -> RJ11_PORT_FAX.PIN))

  ;; Audio Subsystem
  (NET NET_AUDIO_MCLK_45M (CONNECTION OSCILLATOR_AUDIO_PRIMARY.CLK_OUT -> DAC_ESS_SABRE_ES9039PRO.MCLK1))
  (NET NET_AUDIO_MCLK_49M (CONNECTION OSCILLATOR_AUDIO_SECONDARY.CLK_OUT -> DAC_ESS_SABRE_ES9039PRO.MCLK2))
  (NET NET_AUDIO_BUS (CONNECTION DAC_ESS_SABRE_ES9039PRO.I2S_IN -> DSP_DIRAC_LIVE.AUDIO_IN))
  (NET NET_AUDIO_OUT (CONNECTION DSP_DIRAC_LIVE.AUDIO_OUT -> AMP_THX_AAA888.IN))
  (NET NET_AUDIO_SPK_L (CONNECTION AMP_THX_AAA888.OUT_SPK_L -> AUDIO_SPEAKER_STEREO_PAIR.LEFT))
  (NET NET_AUDIO_SPK_R (CONNECTION AMP_THX_AAA888.OUT_SPK_R -> AUDIO_SPEAKER_STEREO_PAIR.RIGHT))
  (NET NET_AUDIO_SUB_BASS (CONNECTION AMP_THX_AAA888.OUT_SUB -> AUDIO_SUB_BASS_TRANSDUCER.IN))
  (NET NET_HEADPHONE_OUT (CONNECTION AMP_THX_AAA888.OUT_HP -> AUDIO_JACK_3.5MM.L/R))

  ;; Security, Hotkeys & Controls
  (NET NET_FINGERPRINT_SPI (CONNECTION FINGERPRINT_SENSOR.SPI -> SECURE_ENCLAVE_COPROCESSOR.SPI_SECURE))
  (NET NET_AI_HOTKEY_TRIGGER (CONNECTION PROGRAMMABLE_AI_HOTKEY.PIN -> SYSTEM_EC.GPIO_AI_KEY_IRQ))
  (NET NET_HW_JUMPER_CFG (CONNECTION HW_CONFIG_JUMPERS -> SYSTEM_EC.GPIO_STRAP_PINS))
  (NET NET_EC_KILL_SWITCH_BUS
    (CONNECTION WIFI_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_WLAN)
    (CONNECTION CELLULAR_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_WWAN)
    (CONNECTION BLUETOOTH_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_BT)
    (CONNECTION NFC_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_NFC)
  )
)    (CONNECTION WIFI_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_WLAN)
    (CONNECTION CELLULAR_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_WWAN)
    (CONNECTION BLUETOOTH_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_BT)
    (CONNECTION NFC_TOGGLE_BUTTON.GPIO -> SYSTEM_EC.KILL_NFC)
  )
)
